# Generated by Django 2.2.14 on 2022-01-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Username')),
                ('prenom', models.CharField(max_length=20, verbose_name='Prenom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('numero', models.CharField(max_length=15, verbose_name='Numero')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Genre')),
            ],
        ),
    ]
