# Generated by Django 2.2.14 on 2022-01-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220126_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=256, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=10)),
            ],
        ),
    ]
